---
name: "Security üõ°Ô∏è"
description: "See a security issue? Let us know"
title: "[Security] <write your issue here>"
labels: ["security", "goal: enhancement"]
---
body:
  - type: textarea
    id: docs_description
    attributes:
      label: "Issue Description"
      description: "Please provide a brief summary of the documentation issue you are experiencing or would like to address."
    validations:
      required: true
  - type: textarea
    id: additional_context_docs
    attributes:
      label: "Additional Context"
      description: "If there is any additional context or information that would be helpful for addressing this issue, please provide it here."

  - type: textarea
    id: screenshots_examples_docs
    attributes:
      label: "Screenshots or Examples (if applicable)"
      description: "Please include relevant screenshots or examples to help illustrate the problem."

  - type: textarea
    id: proposed_solution_security
    attributes:
      label: "Proposed Solution (optional)"
      description: "If you have a proposed solution for the security issue, please provide it here. This can help us solve the problem in a prompt manner."

  - type: checkboxes
    id: terms_checklist_security
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)"
          required: true
        - label: "I have read the [Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
  - type: markdown
    attributes:
      value: "Thank you for taking the time to raise this issue! Your input is greatly appreciated."
